package com.shop.dao;

import com.shop.dao.dataobject.CartItemDataObj;

public interface CartItemDataObjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbg.generated Tue Dec 29 20:05:46 CST 2020
     */
    int deleteByPrimaryKey(Long cartItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbg.generated Tue Dec 29 20:05:46 CST 2020
     */
    int insert(CartItemDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbg.generated Tue Dec 29 20:05:46 CST 2020
     */
    int insertSelective(CartItemDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbg.generated Tue Dec 29 20:05:46 CST 2020
     */
    CartItemDataObj selectByPrimaryKey(Long cartItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbg.generated Tue Dec 29 20:05:46 CST 2020
     */
    int updateByPrimaryKeySelective(CartItemDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbg.generated Tue Dec 29 20:05:46 CST 2020
     */
    int updateByPrimaryKey(CartItemDataObj record);
}