package com.shop.dao;

import com.shop.dao.dataobject.ItemStockDataObj;
import org.apache.ibatis.annotations.Param;

public interface ItemStockDataObjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Sep 18 15:36:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Sep 18 15:36:15 CST 2020
     */
    int insert(ItemStockDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Sep 18 15:36:15 CST 2020
     */
    int insertSelective(ItemStockDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Sep 18 15:36:15 CST 2020
     */
    ItemStockDataObj selectByPrimaryKey(Integer id);

    ItemStockDataObj selectByItemId(Integer itemId);

    int decreaseStock(@Param("itemId")Integer itemId, @Param("amount")Integer amount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Sep 18 15:36:15 CST 2020
     */
    int updateByPrimaryKeySelective(ItemStockDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Sep 18 15:36:15 CST 2020
     */
    int updateByPrimaryKey(ItemStockDataObj record);
}