package com.shop.dao;

import com.shop.dao.dataobject.ItemDataObj;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemDataObjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Sep 18 15:36:15 CST 2020
     */
    List<ItemDataObj> listItem();

    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Sep 18 15:36:15 CST 2020
     */
    int insert(ItemDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Sep 18 15:36:15 CST 2020
     */
    int insertSelective(ItemDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Sep 18 15:36:15 CST 2020
     */
    ItemDataObj selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Sep 18 15:36:15 CST 2020
     */
    int updateByPrimaryKeySelective(ItemDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Sep 18 15:36:15 CST 2020
     */
    int updateByPrimaryKey(ItemDataObj record);

    // This method is applied in stock service
    int increaseSales(@Param("id") Integer id, @Param("amount") Integer amount);
}
