package com.shop.dao;

import com.shop.dao.dataobject.PromoDataObj;

public interface PromoDataObjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Sep 23 11:54:48 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Sep 23 11:54:48 CST 2020
     */
    int insert(PromoDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Sep 23 11:54:48 CST 2020
     */
    int insertSelective(PromoDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Sep 23 11:54:48 CST 2020
     */
    PromoDataObj selectByPrimaryKey(Integer id);

    PromoDataObj selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Sep 23 11:54:48 CST 2020
     */
    int updateByPrimaryKeySelective(PromoDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Sep 23 11:54:48 CST 2020
     */
    int updateByPrimaryKey(PromoDataObj record);


}