package com.shop.dao;

import com.shop.dao.dataobject.SequenceDataObj;

public interface SequenceDataObjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Sep 20 22:37:27 CST 2020
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Sep 20 22:37:27 CST 2020
     */
    int insert(SequenceDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Sep 20 22:37:27 CST 2020
     */
    int insertSelective(SequenceDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Sep 20 22:37:27 CST 2020
     */
    SequenceDataObj selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Sep 20 22:37:27 CST 2020
     */
    int updateByPrimaryKeySelective(SequenceDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Sep 20 22:37:27 CST 2020
     */
    int updateByPrimaryKey(SequenceDataObj record);


    SequenceDataObj getSequenceByName(String name);

}