package com.shop.dao;

import com.shop.dao.dataobject.UserPasswordDataObj;

public interface UserPasswordDataObjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Sep 13 18:58:36 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Sep 13 18:58:36 CST 2020
     */
    int insert(UserPasswordDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Sep 13 18:58:36 CST 2020
     */
    int insertSelective(UserPasswordDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Sep 13 18:58:36 CST 2020
     */
    UserPasswordDataObj selectByPrimaryKey(Integer id);
    UserPasswordDataObj selectByUserId(Integer userId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Sep 13 18:58:36 CST 2020
     */
    int updateByPrimaryKeySelective(UserPasswordDataObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Sep 13 18:58:36 CST 2020
     */
    int updateByPrimaryKey(UserPasswordDataObj record);
}